### ISSUE TITLE
time limit

### ISSUE THREAD

**Issue by smarthorizons** [subhamayd2/day_night_time_picker#7]
Hello, and thank for the plugin, very elegant and nice

can you please add a feature that limits the time user can select. for example I wanted user to select time only between 7 AM to 5 PM.
Also with the ability to allow time selection for every hour or every half hour  or every quarter of hour. i.e they have to either select 7 , 8 , 9 ..etc. 
or 7:30 , 8:30 .. etc. 
or 7:15, 7:30 , 7:45 .. etc

I hope to see these features in this nice time picker

**Comment by SayWut** [comment]
It is not a dream anymore :D
He added it in the last update (Nov 4, 2020)

**Comment by brunoadamalves** [comment]
Yup, I'm looking forward to this feature as well

**Comment by subhamayd2** [comment]
Hi,

I added the features.
Please let me know, if you encounter any issues.

Thanks. 😃

**Comment by SayWut** [comment]
@subhamayd2 the why that you implemented this features isn't precise
First, when the picker is sets to 24 hours format and the `maxHour` is sets to 11 I can slide from 00:00 (0:00 am) to 11:59 (11:59 am)
but when the picker is sets to 12 hours format and the `maxHour` is sets to 11 I can only slide from 0:00 am to 11:59 am and from 0:00 pm and 11:59 pm which as you can see isn't corresponding.

If you treat those properties like it always takes values in 24 format it will be easier for you and the user to know what is the wanted limit
because in 24 hours format you know that the number 11 is always 11:00 (11 am) and if it was in 12 format  you can't know what the number 11 means is it am or pm

Second, is there a way to implement it by list of `TimeOfDay`? 
for example you can add like a `blackListTimes` and `whiteListTimes` that takes list of `TimeOfDay`
if only `blackListTimes` property is set then you can pick any time expect from those in the list
if only `whiteListTimes` property is set then you can pick only the time in the list
if nothing is set then you can pick any time
